name: Build for Release

on:
  push:


jobs:
  known-good-2-7:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: docker run --rm -v "$(pwd)/tmp:/tmp" jamiehewland/alpine-pypy-build:2.7-7.3.1-alpine3.11

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: pypy-2.7
          path: tmp/usession-*/build
          retention-days: 7

  known-good-3-6:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: docker run --rm -v "$(pwd)/tmp:/tmp" jamiehewland/alpine-pypy-build:3.6-7.3.1-alpine3.11

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: pypy-3.6
          path: tmp/usession-*/build
          retention-days: 7