name: Docker

on:
  push:


jobs:
  'docker-3-7':
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: cyb3rjak3/alpine-pypy-builder,ghcr.io/cyb3r-jak3/alpine-pypy-builder
        tags: |
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
        labels: |
          org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/alpine-pypy-builder.git
          org.label-schema.schema-version=1.0.0-rc1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0

    - name: Cache Docker layers
      uses: actions/cache@v2.1.5
      with:
        path: /tmp/.buildx-cache
        key: buildx-slim-${{ github.sha }}
        restore-keys: buildx-slim

    - name: 3.7 Build and Push
      uses: docker/build-push-action@v2.4.0
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v8
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        context: ./3.7/alpine3.12/
        file: ./3.7/alpine3.12/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  # '3.7-release':
  #   runs-on: ubuntu-latest
  #   steps:

  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Build container
  #     run: |
  #       cd 3.7/alpine3.12
  #       docker build --tag pypy-builder .

  #   - name: 3.7 Build and Push
  #     uses: docker/build-push-action@v2.4.0
  #     with:
  #       platforms: linux/amd64,linux/arm64,linux/arm/v8
  #       cache-from: type=local,src=/tmp/.buildx-cache
  #       cache-to: type=local,dest=/tmp/.buildx-cache
  #       push: ${{ startsWith(github.ref, 'refs/tags/v') }}
  #       context: ./3.7/alpine3.12/
  #       file: ./3.7/alpine3.12/Dockerfile
  #       tags: ${{ steps.meta.outputs.tags }}
  #       labels: ${{ steps.meta.outputs.labels }}

  known-good:
      runs-on: ubuntu-latest
      steps:
        - name: Build
          run: docker run --rm -it -v "$(pwd)/tmp:/tmp" jamiehewland/alpine-pypy-build:2.7-7.3.0-alpine3.11

        - name: Check
          run: ls /tmp/
  # '2.7':
  #   runs-on: ubuntu-latest
  #   steps:

  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Login to Docker
  #     uses: docker/login-action@v1 
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}

  #   - name: Login To GitHub
  #     uses: docker/login-action@v1 
  #     with:
  #       registry: ghcr.io
  #       username: ${{ github.repository_owner }}
  #       password: ${{ secrets.CR_PAT }}

  #   - name: Login To GitLab
  #     uses: docker/login-action@v1 
  #     with:
  #       registry: registry.gitlab.com
  #       username: ${{ secrets.GITLAB_USER }}
  #       password: ${{ secrets.GITLAB_TOKEN }}

  #   - name: Docker Meta
  #     id: meta
  #     uses: docker/metadata-action@v3
  #     with:
  #       images: cyb3rjak3/pypy-flask,ghcr.io/cyb3r-jak3/pypy-flask,registry.gitlab.com/cyb3r-jak3/pypy-flask
  #       flavor: |
  #         suffix=-alpine
  #       tags: |
  #         type=ref,event=pr
  #         type=semver,pattern={{version}}
  #         type=semver,pattern={{major}}.{{minor}}
  #         type=sha
  #       labels: |
  #         org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/pypy-flask.git
  #         org.label-schema.schema-version=1.0.0-rc1

  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v1.1.0

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v1.3.0

  #   - name: Cache Docker layers
  #     uses: actions/cache@v2.1.5
  #     with:
  #       path: /tmp/.buildx-cache
  #       key: buildx-alpine-${{ github.sha }}
  #       restore-keys: buildx-alpine

  #   - name: Alpine Build and Push
  #     uses: docker/build-push-action@v2.4.0
  #     with:
  #       platforms: linux/amd64,linux/arm64
  #       cache-from: type=local,src=/tmp/.buildx-cache
  #       cache-to: type=local,dest=/tmp/.buildx-cache
  #       push: ${{ startsWith(github.ref, 'refs/tags/v') }}
  #       file: alpine.Dockerfile
  #       tags: ${{ steps.meta.outputs.tags }}
  #       labels: ${{ steps.meta.outputs.labels }}