name: Docker 3.7

on:
  push:
    branches:
      - '**'
    tags:
      - "v*"
    paths:
      - '3.7/**'
      - .github/workflows/docker-3-7.yml

jobs:
  'docker-3-7':
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: cyb3rjak3/alpine-pypy-builder,ghcr.io/cyb3r-jak3/alpine-pypy-builder
        flavor: |
          latest=false
          suffix=-3.7
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
        labels: |
          org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/alpine-pypy-builder.git
          org.label-schema.schema-version=1.0.0-rc1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0

    - name: Cache Docker layers
      uses: actions/cache@v2.1.5
      with:
        path: /tmp/.buildx-cache
        key: buildx-3.7-${{ github.sha }}
        restore-keys: buildx-3.7

    - name: 3.7 Build and Push
      uses: docker/build-push-action@v2.6.1
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/s390x,linux/386,linux/ppc64le
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        context: ./3.7/alpine3.11/
        file: ./3.7/alpine3.11/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    -
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  'docker-3-7-bootstrap':
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v3.4.0
      with:
        images: cyb3rjak3/alpine-pypy-builder,ghcr.io/cyb3r-jak3/alpine-pypy-builder
        flavor: |
          latest=false
          suffix=-3.7-bootstrap
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
        labels: |
          org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/alpine-pypy-builder.git
          org.label-schema.schema-version=1.0.0-rc1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0

    - name: Cache Docker layers
      uses: actions/cache@v2.1.5
      with:
        path: /tmp/.buildx-cache
        key: buildx-3.7-bootstrap-${{ github.sha }}
        restore-keys: buildx-3.7-bootstrap

    - name: 3.7 Bootstrap Build and Push
      uses: docker/build-push-action@v2.6.1
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/s390x,linux/386,linux/ppc64le
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        context: ./3.7/alpine3.11/
        file: ./3.7/alpine3.11/bootstrap/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    -
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache