name: Docker Images

on:
  push:
    branches:
      - '**'
    tags:
      - "v*"
    paths:
      - '2.7/**'
      - '3.7/**'
      - .github/workflows/docker-2-7.yml
      - .github/workflows/docker-3-7.yml

jobs:

  Docker-Bake:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        target: ['2.7', '2.7-bootstrap', '3.7', '3.7-bootstrap']
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v3.4.0
      with:
        images: cyb3rjak3/alpine-pypy-build,ghcr.io/cyb3r-jak3/alpine-pypy-build
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
        labels: |
          org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/alpine-pypy-builder.git
          org.label-schema.schema-version=1.0.0-rc1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0

    - name: Cache Docker layers
      uses: actions/cache@v2.1.5
      with:
        path: /tmp/.buildx-cache
        key: buildx-${{ matrix.target }}-${{ github.sha }}
        restore-keys: buildx-${{ matrix.target }}-

    # Handling the version tags in the bake file with an arg
    - name: Remove Tags
      # Hacky way to edit the bake file in place
      run: cat <<< $(jq 'del(.target."docker-metadata-action".tags)' ${{ steps.meta.outputs.bake-file }}) > ${{ steps.meta.outputs.bake-file }}

    - name: Build
      uses: docker/bake-action@v1.5.0
      with:
        files: |
          ${{ steps.meta.outputs.bake-file }}
          ./docker-bake.hcl
        targets: ${{ matrix.target }}
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        set: |
          *.cache-from=type=local,src=/tmp/.buildx-cache
          *.cache-to=type=local,mode=max,dest=/tmp/.buildx-cache-new

    -
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache